### ISSUE TITLE
React footer

### ISSUE THREAD

**Issue by mattada** [PlayPickUp/pickup-ui#142]
Need a frontend view of the rails footer recreated in react

Acceptance criteria

- [ ] Mobile responsive

**Comment by sahilangral97** [comment]
Hey @mattada can you please explain what is pickup rails or this rails footer you are referring to.

**Comment by erwstout** [comment]
@sahilangral97 sorry this was a ticket that got put into the wrong place, should have been an internal ticket :-)

**Comment by wliederer** [comment]
made react footer component that is identical to rails on pickup-rails branch - feature/142-react-footer
PR: https://github.com/PlayPickUp/pickup-rails/pull/1258/files

**Comment by wliederer** [comment]
opening web PR https://github.com/PlayPickUp/web/pull/2

**Comment by erwstout** [comment]
Closing. Merged into develop on playpickup/web
