### ISSUE TITLE
Breadcrumbs routing URLs and appending to wrong level

### ISSUE THREAD

**Issue by mattada** [PlayPickUp/pickup-ui#154]
URL: https://www.playpickup.com/sports-betting/arizona-sports-betting
Area of focus: breadcrumbs top left. 

Action: Clicking the top left bread crumb to go back a level, e.g. "sports betting”, appends the URL to the wrong depth of the URL. Resulting in a new URL page of: https://www.playpickup.com/sports-betting/sports-betting
Which is a blank page between header and footer. No error on screen.

**Comment by erwstout** [comment]
I dont believe this is actually in pickup-ui yet, but rather directly in rails @dLars99

**Comment by erwstout** [comment]
After fixing this please follow up on #89 @dLars99
