### ISSUE TITLE
Core | NestedInput Style tweaks

### ISSUE THREAD

**Issue by dLars99** [PlayPickUp/pickup-ui#215]
See Rails issue #1317

- [x]  Make button reflect new styles (Inter font, 0.2 opacity when inactive)
- [ ]  Border should be grey when unfocused (#DFDAE6)
- [x]  Don't show error message until button click

**Comment by wliederer** [comment]
I was added to this ticket to look at the "Dont show error message until buttton click"

i have opened a PR for this
https://github.com/PlayPickUp/prop-picker/pull/72
