### ISSUE TITLE
Turn off ALL CAPS on H3

### ISSUE THREAD

**Issue by mattada** [PlayPickUp/pickup-ui#281]
Specifically targeting the prop cards. 

![image.png](https://images.zenhubusercontent.com/612ea58411d1aad75d4e1eb5/2d281303-751b-4cfd-a1f5-cd8883bcd93a)

https://3.basecamp.com/5198819/buckets/24129764/todos/4465275577

**Comment by erwstout** [comment]
So @mattada this is JUST for those locations and _not_ everywhere? If so, for the person who takes this ticket:

Target specifically this section on the _**Web**_ repo and override the value there - NOT inside of PickUp UI

**Comment by wliederer** [comment]
https://github.com/PlayPickUp/web/pull/376
