### ISSUE TITLE
Investigate using `isolate` plugin for CSS resets

### ISSUE THREAD

**Issue by dLars99** [PlayPickUp/pickup-ui#309]
JSS has a plugin available that's designed to inject the same sort of CSS resetting and shielding we are currently doing manually: https://cssinjs.org/jss-plugin-isolate?v=v10.9.0

Our current solution is a continually moving target, with issues showing up on nearly every new publisher. See if this can be a more permanent, universal solution. If this can be implemented, but substantial refactoring is required, feel free to up the points total on this issue.

**Comment by denvermullets** [comment]
moved to linear
