### ISSUE TITLE
Create Ad Component

### ISSUE THREAD

**Issue by dLars99** [PlayPickUp/pickup-ui#310]
Create an Ad component that can take the following props and render the proper ad based on Ad Manager specs:

- `width`
- `height`
- `url` (optional)
- `background_image`
- `foreground_image` (optional)
- `copy` (optional, HTML to be output by the ad manager WYSIWYG)

![image.png](https://images.zenhubusercontent.com/611aae06e87c3b0f3ad56c07/c5045e8f-a765-4360-a67c-dc3d39594657)

![image.png](https://images.zenhubusercontent.com/611aae06e87c3b0f3ad56c07/197c4aad-53aa-4838-978f-1f8658b7f14f)

**Comment by denvermullets** [comment]
completed
